{"name": "test_user_on_tasks", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>.find_username_in_logout", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"65967942c107fc6ced738644062377bf\")>\n\n    @allure.feature(\"User Tasks\")\n    @allure.story(\"User Logout and Task Verification\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    \n    def test_user_on_tasks(driver):\n        username = \"kate15\"\n        password = \"kate15\"\n    \n        with allure.step(\"Navigate to the login page and authenticate\"):\n            user_on_tasks = LoginPage(driver)\n            user_on_tasks.get_login_page()\n            user_on_tasks.authenticated_user(username, password)\n    \n        with allure.step(\"Verify successful login\"):\n            tasks = TasksPage(driver)\n            tasks.get_success_message()\n            assert \"Вы успешно вошли в систему\" in tasks.get_success_message(), \"User is not authorized\"\n    \n        with allure.step(\"Verify username in logout section\"):\n            tasks.find_username_in_logout()\n>           assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\nE           AssertionError: Another user is authorized\nE           assert 'kate15' in ''\nE            +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>>()\nE            +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>.find_username_in_logout\n\ntests/ui/ui_tests/test_user.py:123: AssertionError"}, "steps": [{"name": "Navigate to the login page and authenticate", "status": "passed", "start": 1742642133186, "stop": 1742642133849}, {"name": "Verify successful login", "status": "passed", "start": 1742642133849, "stop": 1742642133894}, {"name": "Verify username in logout section", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f72ea56c070>.find_username_in_logout\n", "trace": "  File \"/app/tests/ui/ui_tests/test_user.py\", line 123, in test_user_on_tasks\n    assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\n"}, "start": 1742642133894, "stop": 1742642133920}], "start": 1742642133185, "stop": 1742642133924, "uuid": "bf0ea943-0a18-4b77-bfc1-8e86548eb0ef", "historyId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "testCaseId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "fullName": "tests.ui.ui_tests.test_user#test_user_on_tasks", "labels": [{"name": "story", "value": "User Logout and Task Verification"}, {"name": "feature", "value": "User Tasks"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests.ui.ui_tests"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "72ee90207c35"}, {"name": "thread", "value": "20-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.ui_tests.test_user"}]}