{"name": "test_user_on_tasks", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>.find_username_in_logout", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d73f8ca8f2633abbd44ba68402353a87\")>\n\n    @allure.feature(\"User Tasks\")\n    @allure.story(\"User Logout and Task Verification\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    \n    def test_user_on_tasks(driver):\n        username = \"kate15\"\n        password = \"kate15\"\n    \n        with allure.step(\"Navigate to the login page and authenticate\"):\n            user_on_tasks = LoginPage(driver)\n            user_on_tasks.get_login_page()\n            user_on_tasks.authenticated_user(username, password)\n    \n        with allure.step(\"Verify successful login\"):\n            tasks = TasksPage(driver)\n            tasks.get_success_message()\n            assert \"Вы успешно вошли в систему\" in tasks.get_success_message(), \"User is not authorized\"\n    \n        with allure.step(\"Verify username in logout section\"):\n            tasks.find_username_in_logout()\n>           assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\nE           AssertionError: Another user is authorized\nE           assert 'kate15' in ''\nE            +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>>()\nE            +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>.find_username_in_logout\n\ntests/ui/ui_tests/test_user.py:123: AssertionError"}, "steps": [{"name": "Navigate to the login page and authenticate", "status": "passed", "start": 1742642900065, "stop": 1742642900486}, {"name": "Verify successful login", "status": "passed", "start": 1742642900486, "stop": 1742642900709}, {"name": "Verify username in logout section", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0117d98850>.find_username_in_logout\n", "trace": "  File \"/app/tests/ui/ui_tests/test_user.py\", line 123, in test_user_on_tasks\n    assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\n"}, "start": 1742642900709, "stop": 1742642900740}], "start": 1742642900064, "stop": 1742642900751, "uuid": "acf0bc04-2b2e-4322-badd-1b38d59d00bd", "historyId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "testCaseId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "fullName": "tests.ui.ui_tests.test_user#test_user_on_tasks", "labels": [{"name": "feature", "value": "User Tasks"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "User Logout and Task Verification"}, {"name": "parentSuite", "value": "tests.ui.ui_tests"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "4b012a104868"}, {"name": "thread", "value": "19-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.ui_tests.test_user"}]}