{"name": "test_user_on_tasks", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>.find_username_in_logout", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"7e62ec8aba4f2759ddb10131c0600b61\")>\n\n    @allure.feature(\"User Tasks\")\n    @allure.story(\"User Logout and Task Verification\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    \n    def test_user_on_tasks(driver):\n        username = \"kate15\"\n        password = \"kate15\"\n    \n        with allure.step(\"Navigate to the login page and authenticate\"):\n            user_on_tasks = LoginPage(driver)\n            user_on_tasks.get_login_page()\n            user_on_tasks.authenticated_user(username, password)\n    \n        with allure.step(\"Verify successful login\"):\n            tasks1 = TasksPage(driver)\n            tasks1.get_success_message()\n            assert \"Вы успешно вошли в систему\" in tasks1.get_success_message(), \"User is not authorized\"\n    \n        with allure.step(\"Verify username in logout section\"):\n            tasks1.find_username_in_logout()\n>           assert username in tasks1.find_username_in_logout(), \"Another user is authorized\"\nE           AssertionError: Another user is authorized\nE           assert 'kate15' in ''\nE            +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>>()\nE            +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>.find_username_in_logout\n\ntests/ui/ui_tests/test_user.py:123: AssertionError"}, "steps": [{"name": "Navigate to the login page and authenticate", "status": "passed", "start": 1742643104539, "stop": 1742643105849}, {"name": "Verify successful login", "status": "passed", "start": 1742643105849, "stop": 1742643106072}, {"name": "Verify username in logout section", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate15' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f0b5215d2b0>.find_username_in_logout\n", "trace": "  File \"/app/tests/ui/ui_tests/test_user.py\", line 123, in test_user_on_tasks\n    assert username in tasks1.find_username_in_logout(), \"Another user is authorized\"\n"}, "start": 1742643106072, "stop": 1742643106106}], "start": 1742643104539, "stop": 1742643106114, "uuid": "9243d786-d4a0-421f-9322-a2c71d011087", "historyId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "testCaseId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "fullName": "tests.ui.ui_tests.test_user#test_user_on_tasks", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "User Tasks"}, {"name": "story", "value": "User Logout and Task Verification"}, {"name": "parentSuite", "value": "tests.ui.ui_tests"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "cadc5b2277ac"}, {"name": "thread", "value": "19-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.ui_tests.test_user"}]}