{"name": "test_user_on_tasks", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate13' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>.find_username_in_logout", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"fe2d76e88f110896d37f53f46a44e3e7\")>\n\n    @allure.feature(\"User Tasks\")\n    @allure.story(\"User Logout and Task Verification\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    \n    def test_user_on_tasks(driver):\n        username = \"kate13\"\n        password = \"kate13\"\n    \n        with allure.step(\"Navigate to the login page and authenticate\"):\n            user_on_tasks = LoginPage(driver)\n            user_on_tasks.get_login_page()\n            user_on_tasks.authenticated_user(username, password)\n    \n        with allure.step(\"Verify successful login\"):\n            tasks = TasksPage(driver)\n            tasks.get_success_message()\n            assert \"Вы успешно вошли в систему\" in tasks.get_success_message(), \"User is not authorized\"\n    \n        with allure.step(\"Verify username in logout section\"):\n            tasks.find_username_in_logout()\n>           assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\nE           AssertionError: Another user is authorized\nE           assert 'kate13' in ''\nE            +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>>()\nE            +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>.find_username_in_logout\n\ntests/ui/ui_tests/test_user.py:123: AssertionError"}, "steps": [{"name": "Navigate to the login page and authenticate", "status": "passed", "start": 1742640895891, "stop": 1742640896352}, {"name": "Verify successful login", "status": "passed", "start": 1742640896352, "stop": 1742640896577}, {"name": "Verify username in logout section", "status": "failed", "statusDetails": {"message": "AssertionError: Another user is authorized\nassert 'kate13' in ''\n +  where '' = <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>>()\n +    where <bound method TasksPage.find_username_in_logout of <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>> = <tests.ui.pages.tasks_page.TasksPage object at 0x7f7521b98700>.find_username_in_logout\n", "trace": "  File \"/app/tests/ui/ui_tests/test_user.py\", line 123, in test_user_on_tasks\n    assert username in tasks.find_username_in_logout(), \"Another user is authorized\"\n"}, "start": 1742640896577, "stop": 1742640896608}], "start": 1742640895891, "stop": 1742640896611, "uuid": "54a4069b-ec50-492a-a7ae-d7b60816560f", "historyId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "testCaseId": "4c3e7b3a3ad602544e0d0c43f85d6f5c", "fullName": "tests.ui.ui_tests.test_user#test_user_on_tasks", "labels": [{"name": "feature", "value": "User Tasks"}, {"name": "story", "value": "User Logout and Task Verification"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests.ui.ui_tests"}, {"name": "suite", "value": "test_user"}, {"name": "host", "value": "f7fa9af94b06"}, {"name": "thread", "value": "19-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.ui_tests.test_user"}]}